### PR TITLE
admin here will be able to add blog

### PR DESCRIPTION
**Pull request by iradukundairenee**
> #### What does this PR do?
this PR add blog
> #### Description of Task to be completed
> *  admin will add articles that will be visible on client side and admin panel himself.
> #### How should this be manually tested?
>  * clone the repository
> * change to ft-addblog branch
> * go into server folder
> * go into routes folder

### CODE REVIEW

**Review by habinezadalvan — COMMENTED** [review]
Please add a PR description following the proper convention and remember to add a screenshot of the functionlity.

**Comment by iradukundairenee** [comment]
addblog

**Review by habinezadalvan — APPROVED** [review]
LGTM

**Pull request merged**
